/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    fontSize: {
      sm: "0.8rem",
      base: "1rem",
      xl: "1.25rem",
      "2xl": "1.50rem",
      "3xl": "1.75rem",
      "4xl": "2rem",
      "5xl": "2.25rem",
      "6xl": "2.50rem",
      "7xl": "2.75rem",
      "8xl": "3rem",
      "9xl": "4rem",
      "10xl": "5rem",
    },
    fontWeight: {
      thin: "100",
      hairline: "100",
      extralight: "200",
      light: "300",
      normal: "400",
      medium: "500",
      semibold: "600",
      bold: "700",
      extrabold: "800",
      "extra-bold": "800",
      black: "900",
    },
    letterSpacing: {
      tightest: "-.075em",
      tighter: "-.05em",
      tight: "-.025em",
      normal: "0",
      wide: ".025em",
      wider: ".05em",
      widest: ".1em",
      widest: ".25em",
    },
    screens: {
      xs: "220px",
      sm: "420px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
      "3xl": "2000px",
    },
    colors: {
      white: "#fff",
      black: "#000",
      blue: "#1fb6ff",
      purple: "#7e5bef",
      pink: "#ff49db",
      orange: "#ff7849",
      green: "#13ce66",
      yellow: "#ffc82c",
      red: "#FF0000",
      bgClr: "rgb(51 47 47)",
      "gray-dark": "#273444",
      gray: "#8492a6",
      "gray-light": "#d3dce6",
    },
    fontFamily: {
      sans: ["Graphik", "sans-serif"],
      serif: ["Merriweather", "serif"],
    },
    //  By default the spacing scale is inherited by the padding, margin, width, minWidth, maxWidth, height,
    // minHeight, maxHeight, gap, inset, space, translate, scrollMargin, and scrollPadding core plugins.
    spacing: {
      1: "4px",
      2: "8px",
      3: "12px",
      4: "16px",
      5: "20px",
      6: "24px",
      7: "28px",
      8: "32px",
      9: "36px",
    },

    extend: {
      //   spacing: {
      //     128: "32rem",
      //     144: "36rem",
      //   },
      borderRadius: {
        sm: "5px",
        md: "10px",
        lg: "15px",
        xl: "15px",
        "4xl": "20px",
      },
    },
  },
  plugins: [],
};
